# generated by datamodel-codegen:
#   filename:  agent-frontmatter.schema.json
#   timestamp: 2026-03-21T20:29:27+00:00
#
# Regenerate with:
#   uv run datamodel-codegen \
#     --input docs/schemas/agent-frontmatter.schema.json \
#     --output src/mde/hooks/agent_frontmatter_model.py \
#     --input-file-type jsonschema \
#     --output-model-type pydantic_v2.BaseModel \
#     --target-python-version 3.12

from __future__ import annotations

from enum import StrEnum

from pydantic import AnyUrl, BaseModel, ConfigDict, Field, RootModel, conint, constr


class Model(StrEnum):
    sonnet = "sonnet"
    opus = "opus"
    haiku = "haiku"
    inherit = "inherit"


class PermissionMode(StrEnum):
    default = "default"
    acceptEdits = "acceptEdits"
    dontAsk = "dontAsk"
    bypassPermissions = "bypassPermissions"
    plan = "plan"


class Type(StrEnum):
    stdio = "stdio"
    sse = "sse"
    http = "http"


class McpServers(BaseModel):
    type: Type | None = None
    command: str | None = None
    args: list[str] | None = None
    url: AnyUrl | None = None
    env: dict[str, str] | None = None


class Memory(StrEnum):
    user = "user"
    project = "project"
    local = "local"


class Effort(StrEnum):
    low = "low"
    medium = "medium"
    high = "high"
    max = "max"


class Isolation(StrEnum):
    worktree = "worktree"


class HookType(StrEnum):
    command = "command"
    prompt = "prompt"


class Hook(BaseModel):
    type: HookType
    command: str | None = None
    prompt: str | None = None


class HookEventListItem(BaseModel):
    matcher: str | None = None
    hooks: list[Hook] | None = None


class HookEventList(RootModel[list[HookEventListItem]]):
    root: list[HookEventListItem]


class Hooks(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    PreToolUse: HookEventList | None = None
    PostToolUse: HookEventList | None = None
    Stop: HookEventList | None = None


class ClaudeCodeAgentFrontmatter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: constr(pattern=r"^[a-z][a-z0-9-]*$") = Field(
        ...,
        description="Agent identifier in kebab-case. Must match the filename stem.",
    )
    description: constr(min_length=1) = Field(
        ...,
        description="Human-readable description of the agent's purpose and when to use it.",
    )
    tools: str | list[str] | None = Field(
        None,
        description="Tools available to this agent. If omitted, inherits parent's tools.",
    )
    disallowedTools: str | list[str] | None = Field(
        None,
        description="Tools explicitly denied to this agent.",
    )
    model: Model | constr(pattern=r"^claude-") | None = Field(
        None,
        description="Model to use. Named shortcuts or full model ID with claude-* prefix.",
    )
    permissionMode: PermissionMode | None = Field(
        None,
        description="Permission level for the agent's tool use.",
    )
    maxTurns: conint(ge=1) | None = Field(
        None,
        description="Maximum number of conversation turns before the agent stops.",
    )
    skills: list[str] | None = Field(
        None,
        description="Skills to inject into the agent's context.",
    )
    mcpServers: list[str | dict[str, McpServers]] | None = Field(
        None,
        description="MCP servers available to this agent, by name or inline definition.",
    )
    hooks: Hooks | None = Field(None, description="Agent-specific hook handlers.")
    memory: Memory | None = Field(
        None,
        description="Memory scope for the agent's auto-memory.",
    )
    background: bool | None = Field(
        None,
        description="If true, agent runs in the background by default.",
    )
    effort: Effort | None = Field(
        None,
        description="Reasoning effort level for the agent.",
    )
    isolation: Isolation | None = Field(
        None,
        description="Isolation strategy. Currently only 'worktree' is supported.",
    )
