version: 2
updates:
  - package-ecosystem: docker
    directory: "/.devcontainer"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Chicago
