# generated by datamodel-codegen:
#   filename:  docs/schemas/skillsmp/
#   timestamp: 2026-03-21T21:30:49+00:00
#
# Post-generation edits:
#   - Combined 3 schema files into single module (codegen produces per-file output)
#   - Added __all__ for explicit public API
#   - Added populate_by_name=True to Skill model_config (API returns camelCase,
#     but Python code accesses snake_case attributes like skill.github_url)

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field

__all__ = [
    "AISearchData",
    "AISearchResponse",
    "AISearchResult",
    "ErrorDetail",
    "ErrorResponse",
    "Skill",
    "SkillSearchData",
    "SkillSearchResponse",
]


# ── skillsmp-error.schema.json ──


class ErrorDetail(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    code: str = ""
    message: str = ""


class ErrorResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    success: bool = False
    error: ErrorDetail | None = None


# ── skillsmp-ai-search.schema.json ──


class AISearchResult(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    file_id: str = ""
    filename: str = ""
    score: float = 0.0


class AISearchData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    object: str = ""
    search_query: str = ""
    data: Annotated[list[AISearchResult], Field(default_factory=list)]


class AISearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    success: bool
    data: AISearchData | None = None


# ── skillsmp-search.schema.json ──


class Skill(BaseModel):
    model_config = ConfigDict(
        extra="allow",
        populate_by_name=True,
    )
    id: str
    name: str
    author: str
    description: str = ""
    github_url: Annotated[str, Field(alias="githubUrl")] = ""
    skill_url: Annotated[str, Field(alias="skillUrl")] = ""
    stars: int = 0
    updated_at: Annotated[str, Field(alias="updatedAt")] = ""


class SkillSearchData(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    skills: Annotated[list[Skill], Field(default_factory=list)]
    total: int = 0
    page: int = 1
    limit: int = 20


class SkillSearchResponse(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    success: bool
    data: SkillSearchData | None = None
