# generated by datamodel-codegen:
#   filename:  honcho-client.schema.json
#   timestamp: 2026-03-23T21:55:23+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field


class HonchoClientConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    base_url: Annotated[str, Field(description="Honcho API server URL.")] = "http://localhost:8000"
    workspace_id: Annotated[str, Field(description="Workspace ID for scoping all operations.")] = (
        "mde"
    )
    api_key: Annotated[
        str | None, Field(description="API key. Null for no-auth (AUTH_USE_AUTH=false).")
    ] = None
    timeout: Annotated[
        float, Field(description="Request timeout in seconds. Must be positive.", gt=0.0)
    ] = 10
    max_retries: Annotated[int, Field(description="Max retry attempts. 0 for fail-fast.", ge=0)] = 0
