"""Multi-agent statusline renderer with toggleable metrics bar for Claude Code.

Subcommands:
- render: Render statusline (reads stdin JSON, outputs ANSI text)
- toggle: Cycle display mode A/B/C
- show-mode: Print current mode
- toggle-widget: Toggle individual metrics widgets on/off
- show-widgets: Print widget toggle state

Schema: statusline-stdin.schema.json (derived from https://code.claude.com/docs/en/statusline)
Models: models.py (generated by datamodel-code-generator, never hand-edit)
Regenerate: mise run mde:codegen:statusline
"""

from __future__ import annotations

__all__: list[str] = []
