# generated by datamodel-codegen:
#   filename:  statusline-stdin.schema.json
#   timestamp: 2026-03-20T03:03:25+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class Model(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    id: str | None = None
    display_name: str | None = None


class Workspace(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    current_dir: str | None = None
    project_dir: str | None = None


class OutputStyle(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = None


class Cost(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    total_cost_usd: float = 0
    total_duration_ms: float = 0
    total_api_duration_ms: float = 0
    total_lines_added: int = 0
    total_lines_removed: int = 0


class CurrentUsage(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    input_tokens: float = 0
    output_tokens: float = 0
    cache_creation_input_tokens: float = 0
    cache_read_input_tokens: float = 0


class ContextWindow(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    total_input_tokens: float = 0
    total_output_tokens: float = 0
    context_window_size: int = 200000
    used_percentage: Annotated[float | None, Field(description="May be null early in session")] = (
        None
    )
    remaining_percentage: float | None = None
    current_usage: Annotated[
        CurrentUsage | None, Field(description="null before first API call")
    ] = None


class Vim(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    mode: Literal["NORMAL", "INSERT"] | None = None


class Agent(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = None


class Worktree(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    name: str | None = None
    path: str | None = None
    branch: str | None = None
    original_cwd: str | None = None
    original_branch: str | None = None


class StatuslineInput(BaseModel):
    model_config = ConfigDict(
        extra="allow",
    )
    cwd: Annotated[str | None, Field(description="Current working directory")] = None
    session_id: Annotated[str | None, Field(description="Unique session identifier")] = None
    transcript_path: Annotated[
        str | None, Field(description="Path to conversation transcript file")
    ] = None
    version: Annotated[str | None, Field(description="Claude Code version")] = None
    exceeds_200k_tokens: Annotated[
        bool,
        Field(
            description="Whether total tokens exceed 200k (fixed threshold regardless of context window size)"
        ),
    ] = False
    model: Annotated[
        str | Model | None,
        Field(description="Current model (string or object with id + display_name)"),
    ] = None
    workspace: Workspace | None = None
    output_style: OutputStyle | None = None
    cost: Annotated[
        Cost | None,
        Field(
            description="Session cost and duration metrics. Values may arrive as strings — Pydantic coerces automatically."
        ),
    ] = None
    context_window: ContextWindow | None = None
    rate_limits: Annotated[
        dict[str, Any] | None,
        Field(
            description="Rate limit data (v2.1.80). Shape unconfirmed — parsed into claude_agent_sdk.types.RateLimitInfo post-validation."
        ),
    ] = None
    vim: Annotated[Vim | None, Field(description="Absent when vim mode disabled")] = None
    agent: Annotated[Agent | None, Field(description="Absent without --agent flag")] = None
    worktree: Annotated[
        Worktree | None, Field(description="Absent outside --worktree sessions")
    ] = None
