# generated by datamodel-codegen:
#   filename:  statusline-stdin.schema.json
#   timestamp: 2026-03-20T03:13:57+00:00

from __future__ import annotations

from typing import Any, Literal, NotRequired, TypedDict


class Model(TypedDict):
    id: NotRequired[str]
    display_name: NotRequired[str]


class Workspace(TypedDict):
    current_dir: NotRequired[str]
    project_dir: NotRequired[str]


class OutputStyle(TypedDict):
    name: NotRequired[str]


class Cost(TypedDict):
    total_cost_usd: NotRequired[float]
    total_duration_ms: NotRequired[float]
    total_api_duration_ms: NotRequired[float]
    total_lines_added: NotRequired[int]
    total_lines_removed: NotRequired[int]


class CurrentUsage(TypedDict):
    input_tokens: NotRequired[float]
    output_tokens: NotRequired[float]
    cache_creation_input_tokens: NotRequired[float]
    cache_read_input_tokens: NotRequired[float]


class ContextWindow(TypedDict):
    total_input_tokens: NotRequired[float]
    total_output_tokens: NotRequired[float]
    context_window_size: NotRequired[int]
    used_percentage: NotRequired[float | None]
    remaining_percentage: NotRequired[float | None]
    current_usage: NotRequired[CurrentUsage | None]


class Vim(TypedDict):
    mode: NotRequired[Literal["NORMAL", "INSERT"]]


class Agent(TypedDict):
    name: NotRequired[str]


class Worktree(TypedDict):
    name: NotRequired[str]
    path: NotRequired[str]
    branch: NotRequired[str]
    original_cwd: NotRequired[str]
    original_branch: NotRequired[str]


class StatuslineInput(TypedDict):
    cwd: NotRequired[str]
    session_id: NotRequired[str]
    transcript_path: NotRequired[str]
    version: NotRequired[str]
    exceeds_200k_tokens: NotRequired[bool]
    model: NotRequired[str | Model]
    workspace: NotRequired[Workspace]
    output_style: NotRequired[OutputStyle]
    cost: NotRequired[Cost]
    context_window: NotRequired[ContextWindow | None]
    rate_limits: NotRequired[dict[str, Any]]
    vim: NotRequired[Vim | None]
    agent: NotRequired[Agent]
    worktree: NotRequired[Worktree]
