activity_tracker: {}
auth_enabled: false
blocks_storage:
  backend: s3
  s3:
    bucket_name: ${MIMIR_S3_BUCKET}
    region: ${AWS_REGION}
    access_key_id: ${MIMIR_S3_ACCESS_KEY}
    secret_access_key: ${MIMIR_S3_SECRET_KEY}
  tsdb:
    dir: /data/tsdb
compactor:
  data_dir: /data/compactor
  sharding_enabled: true
distributor:
  ring:
    kvstore:
      store: inmemory
ingester:
  ring:
    replication_factor: 1
    kvstore:
      store: inmemory
limits:
  ingestion_burst_size_mb: 32
  ingestion_rate_mb: 16
  max_label_names_per_series: 60
  max_global_series_per_user: 0
memberlist:
  join_members: []
query_frontend:
  parallelize_shardable_queries: true
server:
  http_listen_port: 8080
storage:
  tsdb:
    retention_period: 336h
